Add telegram notifications
petio-team/petio pull request #337
Opened 2021-04-04 16:32 UTC by piitaya

Allow usage of telegram for notifications.

<img width="659" alt="telegram notification" src="https://user-images.githubusercontent.com/5878303/113515243-9c3db700-9573-11eb-95da-3ede18f4bb1a.png">

2021-04-04 16:36 UTC, angrycuban13 requested changes
I'm just nitpicking at the UI stuff but @AshDyson will have the fnal voice on this.

2021-04-04 16:36 UTC, angrycuban13 commented on admin/src/page/settings/general.js
> +            Please enter here your telegram chat config. You can find
Capitalize `telegram`

2021-04-04 16:36 UTC, angrycuban13 commented on admin/src/page/settings/general.js
> +            documentation about telegram bot on{" "}
Capitalize `telegram` and add an `'s` to the end of the word

2021-04-04 16:36 UTC, angrycuban13 commented on admin/src/page/settings/general.js
> +              telegram documentation
Same as the previous 2 comments

2021-04-04 16:40 UTC, piitaya commented on admin/src/page/settings/general.js
> +            Please enter here your telegram chat config. You can find
Done 😊

2021-04-05 13:24 UTC, AshDyson approved these changes

2021-04-05 13:24 UTC, merged

2021-07-04 06:45 UTC, VozDeOuro commented
I would like to give a suggestion to add the notifications in this style 
![image](https://user-images.githubusercontent.com/36045463/124375776-4663d280-dc7a-11eb-8363-13432bdee0b8.png)