Lidarr API client definition
petio-team/petio pull request #718
Opened 2022-07-14 15:14 UTC by anatosun

This is one of the first step towards Music integration into Petio.

EDIT:

The following PR is a work in progress. Its final goal is music integration into Petio. Here are tentative tasks (i.e., subject to being edited):

- [x] Lidarr API client definition
- [ ] Lidarr Downloader definition
- [ ] Musicbrainz integration
- [ ] Frontend adjustments

2022-07-14 16:17 UTC, ADRFranklin requested changes
This is all and good, but I don't think this makes sense right now without the addition of the musicbrainz integration. It's just dead code with no actual use case.

2022-07-14 16:25 UTC, ADRFranklin commented
I should also mention that we follow a strict commit message structure, and that is conventional commits. I'm surprised you were able to commit at all without husky or commit-cli complaining.

2022-07-16 14:00 UTC, fwicht commented
I made the necessary adjustments:
- Removed the commented out code.
- Renamed the function.
- Changed the commit messages.
Furthermore, I believe you're right about this PR not making total sense until the MusicBrainz integration. Let me convert this PR into draft.

2022-07-17 15:19 UTC, ADRFranklin commented
The commit messages still do not follow conventional commits. https://www.conventionalcommits.org/en/v1.0.0/

An example would be `Added Lidarr API client definition` becoming `feat(lidarr): added api definitions`

2025-08-29 08:32 UTC, closed without merging